<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Shipments.BG-ccdb7bbc-b2c7-48d5-b0c8-6cf3a2328402</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
	  
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DevTeam.Services.Identity.Domain\DevTeam.Services.Identity.Domain.csproj" />
    <ProjectReference Include="..\DevTeam.Services.Shipments.APplications\DevTeam.Services.Shipments.Applications.csproj" />
    <ProjectReference Include="..\DevTeam.Services.Shipments.Infrastructure\DevTeam.Services.Shipments.Infrastructure.csproj" />
    <ProjectReference Include="..\SharedKernel\SharedKernel.csproj" />
  </ItemGroup>
</Project>
